sudo: required
services:
- docker

script:
- exit 0

deploy:
  # deploy develop to the staging environment
  - provider: script
    script: echo "a"
    on:
      branch: develop
  # deploy master to production
  - provider: script
    script: scripts/deploy.sh production
    on:
      branch: master
